Fix build failure with ruby 3.0
With ruby 3.0, build fails like:

```
/builddir/build/BUILD/dislocker-0.7.3/src/config.c: In function 'setclearkey':
/builddir/build/BUILD/dislocker-0.7.3/src/config.c:59:13: error: expected identifier or '(' before numeric constant
   59 |         int true = TRUE;
```

This is because ruby 3.0 header will include <stdbool.h>, which defines
"true"/"false", ref:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdbool.h.html

So using "true" as variable must be renamed.